name: Update resource
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */3 * * *'

jobs:
  update-resource:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get resource version
        id: get-resource-version
        run: curl --silent https://api.github.com/repos/yf-dev/majsoul-plus-korean/releases/latest | jq -r .tag_name

      - name: Get resource file
        id: get-resource-file
        run: curl $(curl --silent https://api.github.com/repos/yf-dev/majsoul-plus-korean/releases/latest | jq -r .assets[0].browser_download_url) -L --output resource.zip

      - name: clear resource directory
        run: rm -rf resources

      - name: Unzip resource file
        run: unzip -qq resource.zip "korean/assets/*" "korean/resourcepack.json" -d resources

      - name: Remove resource file
        run: rm resource.zip

      - name: Convert extendRes
        run: python convert-extend-res.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Github Action
          author_email: github-action@nothing.local
          message: "Update resources"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
